name: End-to-end tests
on: push
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        spec:
          [
            cypress/e2e/login.cy.js,
            cypress/e2e/productsPage.cy.js,
            cypress/e2e/sideMenu.cy.js,
            cypress/e2e/cartAndShop.cy.js,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run for ${{ matrix.spec }}
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: "${{ matrix.spec }}"
          spec: ${{ matrix.spec }}
        env:
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
